# Data

We developed a list of economics and economics-adjacent departments in the United States and abroad, using a variety of sources. Beginning in January 2019, a team of research assistants accessed each department website and collected available information on seminar schedules. Each semester we updated our data to include the new set of seminar talks posted online. Some departments maintain past seminar schedules on their websites and so we were able to collect that information; for this paper, we include all departments for which data were available from August 2014 through December 2019.

We restrict our sample to include only talks by scholars who had a Ph.D. at the time (so we exclude graduate students), and external speakers (their institution must be different from that of the host department). We also restrict our sample to talks by scholars who are economists (defined as having an economics or economics-adjacent Ph.D., or being affiliated with an economics department). 

There are `r length(unique(ipeds$school))` departments in our sample, from a broad mix of colleges and universities. `r round(100*length(unique(ipeds$school[ipeds$phd_program==1&!is.na(ipeds$phd_program)]))/length(unique(ipeds$school)))`\% of the departments in our sample have a doctoral program. In terms of geographic location, `r round(100*length(unique(ipeds$school[ipeds$census_region=="Northeast"&!is.na(ipeds$census_region)]))/length(unique(ipeds$school)))`\% are in the U.S. Northeast, `r round(100*length(unique(ipeds$school[ipeds$census_region=="Midwest"&!is.na(ipeds$census_region)]))/length(unique(ipeds$school)))`\% are in the U.S. Midwest, `r round(100*length(unique(ipeds$school[ipeds$census_region=="South"&!is.na(ipeds$census_region)]))/length(unique(ipeds$school)))`\% are in the U.S. South, and `r round(100*length(unique(ipeds$school[ipeds$census_region=="West"&!is.na(ipeds$census_region)]))/length(unique(ipeds$school)))`\% are in the U.S. West. The remaining `r round(100*length(unique(ipeds$school[is.na(ipeds$census_region)]))/length(unique(ipeds$school)))`\% of departments are outside the U.S.

We use RePEc rankings of economics departments to classify the rankings of the departments in our sample.^[Source: \url{https://ideas.repec.org/top/top.econdept.html}; rankings retrieved in August 2019.] 289 departments were ranked. For non-economics departments at the same university, we use the economics department ranking. (For instance, Chicago Booth would have the same ranking as Chicago Economics.) `r round(100*length(unique(ipeds$school[ipeds$repec_semdept=="1-10"]))/length(unique(ipeds$school)), digits=1)`\% of departments in our sample were in the top 10; `r round(100*length(unique(ipeds$school[ipeds$repec_semdept=="11-25"]))/length(unique(ipeds$school)), digits=1)`\% were ranked 11-25; another `r round(100*length(unique(ipeds$school[ipeds$repec_semdept=="26-50"]))/length(unique(ipeds$school)), digits=1)`\% were ranked 26-50; `r round(100*length(unique(ipeds$school[ipeds$repec_semdept=="51-100"]))/length(unique(ipeds$school)), digits=1)`\% were ranked 51-100; `r round(100*length(unique(ipeds$school[ipeds$repec_semdept=="101-289"]))/length(unique(ipeds$school)), digits=1)`\% were ranked 101-289; and `r round(100*length(unique(ipeds$school[ipeds$repec_semdept=="Unranked"]))/length(unique(ipeds$school)), digits=1)`\% were unranked.

We coded the demographic characteristics of the seminar speakers in order to consider the composition of speakers across gender and underrepresented minority (URM) status. To do this, we made our best guess based on individuals' names, photos, citizenship (if listed on their website or CV), and the location of their undergraduate institution. We acknowledge that these are imperfect proxies for actual gender and URM status, and are best interpreted as indicating how that person is perceived by others. 

Coding URM status was particularly complicated, as reasonable people can and do disagree about what the definition of interest should be. We interpret the spirit of URM status as being whether someone grew up as an underrepresented minority, facing the various disadvantages that this implies (fewer role models in economics who look like you, and bias from peers, educators, and supervisors). For individuals born abroad but now working in the United States, it is not clear at what point someone should "count" as a URM scholar. In this paper, we show results using the following definition of URM status: black, Latinx, or Native American, and grew up in U.S. When in doubt, we used the location of the person's undergraduate institution as an indicator of whether the person grew up in the United States.