# Composition of seminar talks and speakers {#seminars}

There are `r format(nrow(ipeds), big.mark=",")` seminar talks in our sample, given by `r format(length(unique(ipeds$id)), big.mark=",")` unique speakers. Since any one individual can give multiple seminar talks, we consider the composition of speakers in two ways: (i) at the seminar talk level (so that the same individual counts multiple times if they gave multiple talks), and (ii) at the speaker level (so an individual counts once no matter how many seminar talks they gave).

## Seminar-level analysis

Column 1 of table \@ref(tab:seminar-sample) presents information on speakers at the seminar level. We find that `r round(100*nrow(ipeds[ipeds$urm_status=="Non-URM female",])/nrow(ipeds), digits=1)`\% of talks were given by non-URM women, `r round(100*nrow(ipeds[ipeds$urm_status=="Non-URM male",])/nrow(ipeds), digits=1)`\% of talks were given by non-URM men, `r round(100*nrow(ipeds[ipeds$urm_status=="URM female",])/nrow(ipeds), digits=1)`\% were given by URM women, and `r round(100*nrow(ipeds[ipeds$urm_status=="URM male",])/nrow(ipeds), digits=1)`\% were given by URM men.

(ref:seminar-sample-caption) Sample of seminars and speakers

```{r, results='asis'}
table_body <- read_csv("0-data/table-1.csv", col_names=TRUE, col_types=cols()) %>%
  mutate(percent=ifelse(is.na(percent), formatC(as.numeric(n), format="d", big.mark=","), formatC(as.numeric(100*percent), format="f", digits = 2))) %>%
  select(-n, -variable) %>%
  pivot_wider(names_from=dimension, values_from=percent) %>%
  mutate(label = gsub("female", "women", label)) %>%
  mutate(label = gsub("male", "men", label)) %>%
  kable(booktabs=TRUE, col.names=c("", "Seminars", "Speakers"), digits=2, align="lrr", format.args=list(big.mark=","), escape=FALSE) %>%
  pack_rows("Demographic group (%)", 2, 5) %>%
  pack_rows("Years since Ph.D. (%)", 6, 8) %>%
  pack_rows("RePEc ranking (%)", 9, 14) %>%
  row_spec(c(1, 5, 8), extra_latex_after = "\\midrule")

writeLines(paste("\\begin{table}\n\\caption{\\label{tab:seminar-sample}Sample of seminars and speakers}\n\\centering", gsub("\\begin{tabular}", "\\begin{tabular}[t]", table_body, fixed=TRUE), "\n\\begin{tablenotes}\n(ref:seminar-sample-note)\n\\end{tablenotes}\n\\begin{tablenotes}[Source]\n(ref:seminar-sample-source)\n\\end{tablenotes}\n\\end{table}\n"))
```

(ref:seminar-sample-note) Sample includes all talks by Ph.D.-economist speakers visiting from other institutions (column 1) and all unique Ph.D.-economist seminar speakers who give at least one talk at a school other than their own (column 2). Ph.D. years are from speakers' CVs. RePEc rankings are of the speakers' home departments; these were retrieved in August 2019, and range from 1 (top) to 289 (bottom). If a speaker gave more than one talk, data in column 2 are based on his/her maximum and minimum years since Ph.D. and RePEc ranking, respectively.

(ref:seminar-sample-source) Department websites and authors' calculations.

`r round(100*nrow(ipeds[ipeds$years_from_phd<6&!is.na(ipeds$years_from_phd),])/nrow(ipeds[!is.na(ipeds$years_from_phd),]), digits=1)`\% of talks were given by junior scholars (those who received their Ph.D. fewer than 6 years earlier). `r round(100*nrow(ipeds[ipeds$years_from_phd>=6&ipeds$years_from_phd<12&!is.na(ipeds$years_from_phd),])/nrow(ipeds[!is.na(ipeds$years_from_phd),]), digits=1)`\% were given by mid-career scholars (received their Ph.D. 6-11 years earlier). `r round(100*nrow(ipeds[ipeds$years_from_phd>=12&!is.na(ipeds$years_from_phd),])/nrow(ipeds[!is.na(ipeds$years_from_phd),]), digits=1)`\% of talks were given by senior scholars (received their Ph.D. 12$+$ years earlier).

`r round(100*nrow(ipeds[ipeds$repec_owndept=="1-10",])/nrow(ipeds), digits=1)`\% of talks were given by scholars from the top-10 departments. `r round(100*nrow(ipeds[ipeds$repec_owndept=="11-25",])/nrow(ipeds), digits=1)`\% were given by scholars from departments ranked 11-25, `r round(100*nrow(ipeds[ipeds$repec_owndept=="26-50",])/nrow(ipeds), digits=1)`\% by scholars from departments ranked 26-50, `r round(100*nrow(ipeds[ipeds$repec_owndept=="51-100",])/nrow(ipeds), digits=1)`\% by scholars from departments ranked 51-100, `r round(100*nrow(ipeds[ipeds$repec_owndept=="101-289",])/nrow(ipeds), digits=1)`\% by scholars from departments ranked 101-289; and the remaining `r round(100*nrow(ipeds[ipeds$repec_owndept=="Unranked",])/nrow(ipeds), digits=1)`\% of talks were given by scholars from unranked departments.  (Note that unranked departments include those outside the top 289, as well as non-academic institutions in industry and government.)

## Speaker-level analysis

Column 2 of table \@ref(tab:seminar-sample) shows descriptive statistics for the sample of unique speakers. `r format(round(100*length(unique(ipeds$id[ipeds$urm_status=="Non-URM female"]))/length(unique(ipeds$id)), digits=1), nsmall=1)`\% of speakers were non-URM women; `r round(100*length(unique(ipeds$id[ipeds$urm_status=="Non-URM male"]))/length(unique(ipeds$id)), digits=1)`\% of speakers were non-URM men; `r round(100*length(unique(ipeds$id[ipeds$urm_status=="URM female"]))/length(unique(ipeds$id)), digits=1)`\% of speakers were URM women, and `r round(100*length(unique(ipeds$id[ipeds$urm_status=="URM male"]))/length(unique(ipeds$id)), digits=1)`\% of speakers were URM men.

`r round(100*nrow(subset(ipeds[!is.na(ipeds$years_from_phd),] %>% group_by(id) %>% summarise(years_from_phd=max(years_from_phd)), subset=years_from_phd<6))/length(unique(ipeds$id[!is.na(ipeds$years_from_phd)])), digits=1)`\% of speakers were junior scholars; `r round(100*nrow(subset(ipeds[!is.na(ipeds$years_from_phd),] %>% group_by(id) %>% summarise(years_from_phd=max(years_from_phd)), subset=years_from_phd>=6&years_from_phd<12))/length(unique(ipeds$id[!is.na(ipeds$years_from_phd)])), digits=1)`\% were mid-career scholars; and `r format(round(100*nrow(subset(ipeds[!is.na(ipeds$years_from_phd),] %>% group_by(id) %>% summarise(years_from_phd=max(years_from_phd)), subset=years_from_phd>=12))/length(unique(ipeds$id[!is.na(ipeds$years_from_phd)])), digits=1), nsmall=1)`\% of speakers were senior scholars.

`r round(100*nrow(subset(ipeds %>% group_by(id) %>% summarise(repec_owndept=min(repec_owndept)), subset=repec_owndept=="1-10"))/length(unique(ipeds$id)), digits=1)`\% of speakers were from top-10 departments. `r round(100*nrow(subset(ipeds %>% group_by(id) %>% summarise(repec_owndept=min(repec_owndept)), subset=repec_owndept=="11-25"))/length(unique(ipeds$id)), digits=1)`\% were from departments ranked 11-25; `r round(100*nrow(subset(ipeds %>% group_by(id) %>% summarise(repec_owndept=min(repec_owndept)), subset=repec_owndept=="26-50"))/length(unique(ipeds$id)), digits=1)`\% were from departments ranked 26-50; `r round(100*nrow(subset(ipeds %>% group_by(id) %>% summarise(repec_owndept=min(repec_owndept)), subset=repec_owndept=="51-100"))/length(unique(ipeds$id)), digits=1)`\% were from departments ranked 51-100; `r round(100*nrow(subset(ipeds %>% group_by(id) %>% summarise(repec_owndept=min(repec_owndept)), subset=repec_owndept=="101-289"))/length(unique(ipeds$id)), digits=1)`\% were from departments ranked 101-289; and `r round(100*nrow(subset(ipeds %>% group_by(id) %>% summarise(repec_owndept=min(repec_owndept)), subset=repec_owndept=="Unranked"))/length(unique(ipeds$id)), digits=1)`\% were from departments that were unranked. The differences between these numbers and the seminar-level averages in column 1 imply that a disproportionate share of people from the top 25 departments appear in our sample for more than one talk.

To be included in our sample, a scholar must have given at least one talk during this period. Conditional on giving at least one talk, each non-URM woman in our sample gave `r round(mean(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="Non-URM female")$n), digits=1)` talks on average (median = `r median(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="Non-URM female")$n)`, max = `r max(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="Non-URM female")$n)`), each non-URM man gave `r format(round(mean(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="Non-URM male")$n), digits=1), nsmall=1)` talks (median = `r round(median(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="Non-URM male")$n), digits=1)`, max = `r round(max(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="Non-URM male")$n), digits=1)`), each URM woman gave `r round(mean(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="URM female")$n), digits=1)` talks (median = `r round(median(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="URM female")$n), digits=1)`, max = `r round(max(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="URM female")$n), digits=1)`), and each URM man gave `r round(mean(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="URM male")$n), digits=1)` talks (median = `r round(median(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="URM male")$n), digits=1)`, max = `r round(max(subset(ipeds %>% group_by(id, urm_status) %>% tally(), subset=urm_status=="URM male")$n), digits=1)`). 
