# Seminars at top departments

Opportunities to speak at top departments are of particular value to academic scholars. Where are the speakers who visit those departments drawn from?

`r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM female",])/nrow(ipeds[ipeds$urm_status=="Non-URM female",]))`\% of the `r format(nrow(ipeds[ipeds$urm_status=="Non-URM female",]), big.mark=",")` talks given by non-URM women were at top-25 departments. Among these talks, `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM female"&ipeds$repec_owndept<="11-25",])/nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM female",]))`\% were given by scholars who were themselves affiliated with a top-25 department; only `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM female"&ipeds$repec_owndept=="Unranked",])/nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM female",]))`\% were by scholars at unranked departments.

`r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM male",])/nrow(ipeds[ipeds$urm_status=="Non-URM male",]))`\% of the `r format(nrow(ipeds[ipeds$urm_status=="Non-URM male",]), big.mark=",")` talks given by non-URM men were at top-25 departments. `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM male"&ipeds$repec_owndept<="11-25",])/nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM male",]))`\% of those speakers were also from top-25 departments; `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM male"&ipeds$repec_owndept=="Unranked",])/nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="Non-URM male",]))`\% were from unranked departments.

Among talks given by URM women, `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="URM female",])/nrow(ipeds[ipeds$urm_status=="URM female",]))`\% of their `r nrow(ipeds[ipeds$urm_status=="URM female",])` talks were at top-25 departments. `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="URM female"&ipeds$repec_owndept<="11-25",])/nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="URM female",]))`\% of those speakers were themselves from a top-25 department, while `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="URM female"&ipeds$repec_owndept=="Unranked",])/nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="URM female",]))`\% were from unranked departments.

For URM men, `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="URM male",])/nrow(ipeds[ipeds$urm_status=="URM male",]))`\% of their `r nrow(ipeds[ipeds$urm_status=="URM male",])` talks were at top-25 departments and `r round(100*nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="URM male"&ipeds$repec_owndept<="11-25",])/nrow(ipeds[ipeds$repec_semdept<="11-25"&ipeds$urm_status=="URM male",]))`\% of those speakers were also from a top-25 department. None were from unranked departments.