# Discussion

How should we interpret the numbers presented above? Are seminar series sufficiently diverse, or should departments try to invite more women and URM scholars to present their work?

We do not yet have a clear answer to this question. One useful point of reference is the current composition of the profession. The best numbers on the share of economists who are women or URM come from surveys conducted by CSWEP and CSMGEP, respectively. The numbers we would like to know are the shares of the full pool of active economics researchers in each demographic group. These surveys do not quite tell us this, but they provide several metrics that are useful proxies.

In 2019, 21.2\% of all tenure-track faculty were women, and 24.3\% of all faculty were women \citep{cswep2020}. This does not include women economists who work outside of academia in government, industry, or think tanks. Many of those economists work on academic research and so should be considered part of the pool of potential speakers. For this reason, the total number of economics Ph.D.s granted might be a better reference point. In 2019, 32.2\% of all economics Ph.D.s were granted to women; this number has held roughly steady (if anything it has fallen a bit) since 2010 \citep{cswep2020}.

We find that about `r round(100*length(unique(ipeds$id[ipeds$urm_status=="Non-URM female"|ipeds$urm_status=="URM female"]))/length(unique(ipeds$id)))`\% of the seminar speakers in our sample are women. This is about the same as the share of tenure-track economics faculty who are women, but it is much lower than the share of new economics Ph.D.s granted to women.

In 2018, 9.9\% of new economics Ph.D.s were awarded to URM scholars \citep{csmgep2020}.^[The CSMGEP report defines URM as black, Latinx, or Native American scholars who are U.S. citizens or permanent residents---a slightly broader definition than the one we are using here.] 6.8\% of new economics Ph.D.s were awarded to URM women \citep{csmgep2020}. The best data available suggest that 7.3\% of full-time faculty are URM scholars \citep{csmgep2020}.

We find that about `r round(100*length(unique(ipeds$id[ipeds$urm_status=="URM female"|ipeds$urm_status=="URM male"]))/length(unique(ipeds$id)), digits=1)`\% of speakers are URMs. This number is low relative to every metric above. And, as highlighted in the text, about two-thirds of departments did not invite any URM scholars to speak during the entire sample period.

All that said, our view is that the optimal target for the share of seminar speakers who are women or URM is not the current composition of the profession, but the composition we *aspire* to achieve. There are many reasons to believe that the current lack of diversity in the economics profession represents a highly-inefficient equilibrium \citep{doleac_jel, Moon2020, lundberg_stearns}. Many have lamented the status quo. The question facing all of us now is: How do we change it \citep{buckles}?

Given the role of invited seminar talks in improving and disseminating research, building scholars' networks, and connecting graduate students and junior faculty with role models who look like them, it is likely that the composition of seminar talks is a cause (not simply a consequence) of the composition of the profession.

To the extent that seminar talks have a causal effect on scholars' trajectories within the profession, one relatively low-cost way to provide women and URM scholars more opportunity to succeed in economics is to invite more scholars from underrepresented groups to give seminar talks.^[This may require external funding from professional organizations like the AEA to internalize the positive externalities that departments are not currently considering.] We do not yet know how much of an effect this could have; this will be an important area for future work. But we suspect that increasing the diversity of seminar series in economics departments in the U.S. and abroad could be a highly-effective way to reach the new, more diverse equilibrium we desire.
